### PR TITLE
SNAP-3567_lib-gdal

### PR DESCRIPTION
**Pull request by a-draghici**
Fix for [SNAP-3567](https://senbox.atlassian.net/browse/SNAP-3567).

[SNAP-3567]: https://senbox.atlassian.net/browse/SNAP-3567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by TomBlock — COMMENTED** [review]
I cannot say anything about GDAL integration ...

**Comment by a-draghici** [comment]
> I cannot say anything about GDAL integration ...

Do you can test the new internal GDAL distribution integration on your platforms, to check it on other platforms, outside development?

**Review by TomBlock — COMMENTED** [review]
Build successful on Win10, Linux and MacOs 14.1.1

**Review by TomBlock — COMMENTED** [review]
Failures in reader tests on Win 10 and Linux, see my mail.

**Comment by dianaharosa** [comment]
Hi Tom, 
Regarding the java.lang.ArrayIndexOutOfBoundsException, the issue is fixed and will be committed on the master branch today. We are currently running the Reader Tests.

**Comment by TomBlock** [comment]
Ok, thanks. Then I'm waiting on yoour update. You need to merge master into this PR - I wasn't able to compile snap-desktop before doing so.

**Comment by dianaharosa** [comment]
ArrayIndexOutOfBoundsException fix available on branch SNAP-3567_lib-gdal

**Comment by a-draghici** [comment]
> Hi Adrian, there seems to be still an issue with this. running the reader tests on Win10:
> 
> [ERROR] Errors: [ERROR] org.esa.snap.dataio.ProductReaderAcceptanceTest.testReadIntendedProductContent [ERROR] Run 1: ProductReaderAcceptanceTest.testReadIntendedProductContent:216 Throwable [S5P_NRTI_L2__NO2____20180729T113636] S5P_NRTI_L2__NO2____20180729T113636 has no GeoCoding [ERROR] Run 2: ProductReaderAcceptanceTest.testReadIntendedProductContent:216 Throwable [S2L3-60m-Darmstadt] S2L3-60m-Darmstadt band/variable: quality_mosaic_info_60m Pixel(558,875)- caused ArrayIndexOutOfBoundsException java.lang.ArrayIndexOutOfBoundsException: (x < 0) || (y < 0) || (x >= 512) || (y >= 512) for x=558,y=875 at org.esa.snap.core.util.jai.SingleBandedSampleModel.checkBounds(SingleBandedSampleModel.java:413) at org.esa.snap.core.util.jai.SingleBandedSampleModel.getSampleFloat(SingleBandedSampleModel.java:341) at java.desktop/java.awt.image.Raster.getSampleFloat(Raster.java:1755) at org.esa.snap.core.datamodel.RasterDataNode.getSampleFloat(RasterDataNode.java:1102) at org.esa.snap.dataio.ContentAssert.testExpectedBand(ContentAssert.java:233)

Hi Tom,
We made the final changes.
Please re-check it.
Thank you.

Regards
Adrian

**Review by dianaharosa — APPROVED** [review]

**Review by TomBlock — APPROVED** [review]
Seems to be working now

**Pull request merged**
