### PR TITLE
Replaced reflective calls to GDAL bindings with method handles

### PR DESCRIPTION
**Pull request by kraftek**
Using MethodHandles is almost as fast as direct method calls and faster than calling methods via reflection.

### CODE REVIEW

**Review by dianaharosa — APPROVED** [review]

**Comment by fredsnap** [comment]
@kraftek As far I can see on [tests results](https://gitlab.com/senbox-org/snap-engine/-/pipelines/871700386/test_report) the 3 fails because of unreachable test data.
I tried to cURL it from my pc and from the cluster : same result.
Are we sure that the file is reachable ?

**Comment by TomBlock** [comment]
Thre failures on missing test data are in the WatermaskClassifierTest - this is completely unrelated to this PR. I am fixing that ...

**Comment by marpet** [comment]
@kraftek Can you do it again please? Something went wrong. I think it wasn't well configured.

**Review by TomBlock — APPROVED** [review]
I'm not the GDAL expert and trust on your solution here

**Pull request merged**
