### PR TITLE
fix extraction parameter of the sta adapter engine

### PR DESCRIPTION
**Pull request by Florian1209**
fix in case of null parameter authorized in the descriptor config file

### CODE REVIEW

**Comment by kraftek** [comment]
What is the use case that triggered this?

**Comment by Florian1209** [comment]
For example during the MAJA plugins feature developpement, I was encounters issue with optional array parameters.
The sta adapters don't worked with array null (it was optional). The option in descriptor was correctly configured.

**Review by marpet — COMMENTED** [review]
I've nothing to complain. But I can't approve this. I'm not responsible for the STA.

**Comment by marpet** [comment]
Issue is already closed

**Pull request closed without merging**
