### PR TITLE
including esa_snappy in build

### PR DESCRIPTION
**Pull request by marpet**
Please review this branch with the installer if the python integration works will. If so merge and delete the branch, please.

### CODE REVIEW

**Comment by dolaf** [comment]
Integration works well on Win10, but on an Ubuntu Linux VM, the option '--snappy' is not recognized when snappy_conf is ececuted. This means that the esa_snappy module is obviously not found from the repository. What could be different there? 
snappy_conf_ubuntu

**Comment by marpet** [comment]
Is the esa_snappy dependency located in the 'snap' cluster? Should be in<installDir>/snap/modules

**Comment by dolaf** [comment]
Works fine now also for Linux. Installer now also includes Python configuration GUI (as in earlier SNAPs) for esa_snappy.

**Review by dolaf — APPROVED** [review]
Looks all fine to me.

**Pull request merged**
