### PR TITLE
(SNAP-1400) JP2 reader - special case for EPSG:4326 (correct geolocat…

### PR DESCRIPTION
**Pull request by oanahogoiu**
JP2 reader - special case for EPSG:4326 (correct geolocation and image rotation)

### CODE REVIEW

**Review by marpet — COMMENTED** [review]
Looks fine so far.
I just wonder if different order of lat and lon is an issue of a certain data provider, or is it specified in the specs like this?

**Comment by oanahogoiu** [comment]
Marco, I had the same doubt at the beginning, but it's specified in the specs like that: https://epsg.org/crs_4326/WGS-84.html
It seems that GDAL also made this change and documented it: https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order

**Comment by marpet** [comment]
Yes, true.
But this applies to all Geographic 2D CRS. Maybe it is worth to instantiate the CRS and check its dimension order.
Maybe by investigating the axis by:
                CoordinateReferenceSystem mapCRS = CRS.decode(epsgCode);
                mapCRS.getCoordinateSystem().getAxis(0).getDirection();
or
                mapCRS.getCoordinateSystem().getAxis(0).getAbbreviation();

Not sure what is appropriate. 
This way it would be more generic.

**Comment by marpet** [comment]
The difference between the two is that 4326 is a GeoGraphic CRS and UTM is a projected CRS.
If you check the result of
`CRS.decode("EPSG:3035")`
then you see that this is also projected but has a different order of 32620. So, it seems to be necessary to analyse the crs. To check for the direction name seems to be a good way.
For the most cases your solution will work. But might fail in other (edge) cases.
But you could deal with them when they occur and go on with your current solution.

**Review by marpet — APPROVED** [review]

**Pull request merged**
