### PR TITLE
Terminate AddElevation op during the gpt tests

### PR DESCRIPTION
**Pull request by Florian1209**
The gpt test of the AddElevationTest_S2 doesn't no end.

### CODE REVIEW

**Comment by Florian1209** [comment]
The AddElevationTest_S2 does no end on jenkins server. But the local execution works.
Also, this test on graphbuilder does no end sometime. Do you know what's wrong in the AddElevation operator?

**Comment by marpet** [comment]
Sorry, no idea. Could it be that sometimes the DEM is not downloading. Locally the DEM might be already downloaded.
Maybe @lveci has an idea?

**Comment by Florian1209** [comment]
The gpt test show 
```>> INFO: org.esa.snap.core.dataop.dem.ElevationFile: http retrieving https://download.esa.int/step/auxdata/dem/SRTM90/tiff/srtm_56_10.zip```
```>> INFO: org.esa.snap.engine_utilities.download.DownloadableContentImpl: http retrieving http://step.esa.int/auxdata/dem/egm96/ww15mgh_b.zip```
```>> INFO: org.hsqldb.persist.Logger: Database closed```
The download seem to be done. @lveci  Or it could be good to add log of the download status.

**Comment by lveci** [comment]
This could be related to what Christiano was seeing. Other tests that use the dem don't seem to have the same problem.
The purpose of this test is just to add elevation to an S2 product?

**Review by lveci — APPROVED** [review]

**Comment by Florian1209** [comment]
Yes, just DEM addtion on S2 product.
Sometime the test pass with succedeed, sometime it suspend gpt test (#12277).
For now it 's the next test AddElevationTest_S2_ACE30 it 's suspended gpt test #12278.

**Pull request merged**
